FROM python

WORKDIR /app
COPY ./sorce/ /app/

RUN pip install Flask
RUN pip install pandas
RUN pip install sqlalchemy
RUN pip install PyMySQL
RUN pip install schedule
RUN pip install xgboost
RUN pip install sklearn

CMD ["python", "main.py"]