version: '3'

services:
  main:
    image: hack-u-main
    build: ./main/
    container_name: hack-u-main
    ports:
     - 5000:5000
    depends_on:
     - mysql
    tty: true

  model:
    image: hack-u-model
    build: ./model/
    container_name: hack-u-model
    expose:
     - 5050
    depends_on:
     - mysql
    tty: True
 
  mysql:
    image: hack-u-mysql
    build: ./db/
    container_name: hack-u-mysql
    expose:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hack-u-db
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    tty: True