FROM python

WORKDIR /app
COPY ./sorce/ /app/

RUN pip install Flask
RUN pip install pandas
RUN pip install mysql-connector-python
RUN pip install requests 
RUN pip install flask-cors


CMD ["python", "main.py"]